// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkUrHilfc_hZxo6PEPeN2uxPyMyJ4iYBM',
    appId: '1:89764106891:web:65efd2f38b413054d87a8e',
    messagingSenderId: '89764106891',
    projectId: 'laneoptimization-a75b3',
    authDomain: 'laneoptimization-a75b3.firebaseapp.com',
    storageBucket: 'laneoptimization-a75b3.firebasestorage.app',
    measurementId: 'G-CM2KE4FHLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDONHZfUduyQ-5O1_HoA53RQmHcI7dLXk8',
    appId: '1:89764106891:android:7a55333baeb8d41bd87a8e',
    messagingSenderId: '89764106891',
    projectId: 'laneoptimization-a75b3',
    storageBucket: 'laneoptimization-a75b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJdBNYV9irVLThA7akMr6kBhLi9zPDxFM',
    appId: '1:89764106891:ios:0ccb409210413d70d87a8e',
    messagingSenderId: '89764106891',
    projectId: 'laneoptimization-a75b3',
    storageBucket: 'laneoptimization-a75b3.firebasestorage.app',
    iosBundleId: 'com.example.dscLaneOptimizationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJdBNYV9irVLThA7akMr6kBhLi9zPDxFM',
    appId: '1:89764106891:ios:0ccb409210413d70d87a8e',
    messagingSenderId: '89764106891',
    projectId: 'laneoptimization-a75b3',
    storageBucket: 'laneoptimization-a75b3.firebasestorage.app',
    iosBundleId: 'com.example.dscLaneOptimizationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkUrHilfc_hZxo6PEPeN2uxPyMyJ4iYBM',
    appId: '1:89764106891:web:8fbef6ba3c21dbd8d87a8e',
    messagingSenderId: '89764106891',
    projectId: 'laneoptimization-a75b3',
    authDomain: 'laneoptimization-a75b3.firebaseapp.com',
    storageBucket: 'laneoptimization-a75b3.firebasestorage.app',
    measurementId: 'G-M46E1FTL02',
  );
}
